// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAble_Data
{
    public partial class MenuItem
    {
        public MenuItem()
        {
            OrderMenuItem = new HashSet<OrderMenuItem>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public int? MenuItemCategoryId { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual MenuItemCategory MenuItemCategory { get; set; }
        public virtual User ModifiedByNavigation { get; set; }
        public virtual ICollection<OrderMenuItem> OrderMenuItem { get; set; }
    }
}