// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAble_Data
{
    public partial class Orders
    {
        public Orders()
        {
            OrderMenuItems = new HashSet<OrderMenuItems>();
            OrderTaxes = new HashSet<OrderTaxes>();
        }

        public int Id { get; set; }
        public int? DiscountId { get; set; }
        public decimal SubTotal { get; set; }
        public decimal PreTaxTotal { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public decimal Total { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual Users CreatedByNavigation { get; set; }
        public virtual Discounts Discount { get; set; }
        public virtual ICollection<OrderMenuItems> OrderMenuItems { get; set; }
        public virtual ICollection<OrderTaxes> OrderTaxes { get; set; }
    }
}