// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAble_Data
{
    public partial class OrderTaxes
    {
        public int OrderId { get; set; }
        public int TaxId { get; set; }

        public virtual Orders Order { get; set; }
        public virtual Taxes Tax { get; set; }
    }
}