// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAble_Data
{
    public partial class Order
    {
        public Order()
        {
            OrderMenuItem = new HashSet<OrderMenuItem>();
            OrderTax = new HashSet<OrderTax>();
        }

        public int Id { get; set; }
        public int? DiscountId { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual ICollection<OrderMenuItem> OrderMenuItem { get; set; }
        public virtual ICollection<OrderTax> OrderTax { get; set; }
    }
}