// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAble_Data
{
    public partial class User
    {
        public User()
        {
            DiscountCreatedByNavigation = new HashSet<Discount>();
            DiscountModifiedByNavigation = new HashSet<Discount>();
            InverseCreatedByNavigation = new HashSet<User>();
            InverseModifiedByNavigation = new HashSet<User>();
            MenuItemCategoryCreatedByNavigation = new HashSet<MenuItemCategory>();
            MenuItemCategoryModifiedByNavigation = new HashSet<MenuItemCategory>();
            MenuItemCreatedByNavigation = new HashSet<MenuItem>();
            MenuItemModifiedByNavigation = new HashSet<MenuItem>();
            Order = new HashSet<Order>();
            TaxCreatedByNavigation = new HashSet<Tax>();
            TaxModifiedByNavigation = new HashSet<Tax>();
            UserPassword = new HashSet<UserPassword>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public UserType UserType { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual User ModifiedByNavigation { get; set; }
        public virtual ICollection<Discount> DiscountCreatedByNavigation { get; set; }
        public virtual ICollection<Discount> DiscountModifiedByNavigation { get; set; }
        public virtual ICollection<User> InverseCreatedByNavigation { get; set; }
        public virtual ICollection<User> InverseModifiedByNavigation { get; set; }
        public virtual ICollection<MenuItemCategory> MenuItemCategoryCreatedByNavigation { get; set; }
        public virtual ICollection<MenuItemCategory> MenuItemCategoryModifiedByNavigation { get; set; }
        public virtual ICollection<MenuItem> MenuItemCreatedByNavigation { get; set; }
        public virtual ICollection<MenuItem> MenuItemModifiedByNavigation { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Tax> TaxCreatedByNavigation { get; set; }
        public virtual ICollection<Tax> TaxModifiedByNavigation { get; set; }
        public virtual ICollection<UserPassword> UserPassword { get; set; }
    }

    public enum UserType
    {
        Manager = 0,
        Server = 1
    }
}