// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAble_Data
{
    public partial class Users
    {
        public Users()
        {
            DiscountsCreatedByNavigation = new HashSet<Discounts>();
            DiscountsModifiedByNavigation = new HashSet<Discounts>();
            InverseCreatedByNavigation = new HashSet<Users>();
            InverseModifiedByNavigation = new HashSet<Users>();
            MenuItemCategoriesCreatedByNavigation = new HashSet<MenuItemCategories>();
            MenuItemCategoriesModifiedByNavigation = new HashSet<MenuItemCategories>();
            MenuItemsCreatedByNavigation = new HashSet<MenuItems>();
            MenuItemsModifiedByNavigation = new HashSet<MenuItems>();
            Orders = new HashSet<Orders>();
            TaxesCreatedByNavigation = new HashSet<Taxes>();
            TaxesModifiedByNavigation = new HashSet<Taxes>();
            UserPasswords = new HashSet<UserPasswords>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int UserRoleId { get; set; }
        public bool Active { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        public virtual Users CreatedByNavigation { get; set; }
        public virtual Users ModifiedByNavigation { get; set; }
        public virtual UserRoles UserRole { get; set; }
        public virtual ICollection<Discounts> DiscountsCreatedByNavigation { get; set; }
        public virtual ICollection<Discounts> DiscountsModifiedByNavigation { get; set; }
        public virtual ICollection<Users> InverseCreatedByNavigation { get; set; }
        public virtual ICollection<Users> InverseModifiedByNavigation { get; set; }
        public virtual ICollection<MenuItemCategories> MenuItemCategoriesCreatedByNavigation { get; set; }
        public virtual ICollection<MenuItemCategories> MenuItemCategoriesModifiedByNavigation { get; set; }
        public virtual ICollection<MenuItems> MenuItemsCreatedByNavigation { get; set; }
        public virtual ICollection<MenuItems> MenuItemsModifiedByNavigation { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Taxes> TaxesCreatedByNavigation { get; set; }
        public virtual ICollection<Taxes> TaxesModifiedByNavigation { get; set; }
        public virtual ICollection<UserPasswords> UserPasswords { get; set; }
    }
}